export interface UserDua {
  id: string;
  title?: string;
  arabicText: string;
  transliteration: string;
  englishMeaning: string;
  source: string;
  category: string;
  isBuiltIn?: boolean;
}

// Major everyday duas from authentic sources. All are built-in but removable
// from the library; users can also add their own. Ordered roughly by a daily
// flow (waking → prayer → out & about → evening → sleep).
export const UNIVERSAL_DUAS: UserDua[] = [
  {
    id: 'dua_waking',
    title: 'Upon Waking',
    arabicText: 'الْحَمْدُ لِلَّهِ الَّذِي أَحْيَانَا بَعْدَ مَا أَمَاتَنَا وَإِلَيْهِ النُّشُورُ',
    transliteration: "Alhamdulillahil-ladhi ahyana ba'da ma amatana wa ilayhin-nushur",
    englishMeaning: 'All praise is for Allah who gave us life after He caused us to die, and to Him is the resurrection.',
    source: 'Sahih al-Bukhari',
    category: 'Sleep',
    isBuiltIn: true,
  },
  {
    id: 'dua_morning',
    title: 'Morning Adhkar',
    arabicText: 'أَصْبَحْنَا وَأَصْبَحَ الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ، لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ',
    transliteration: 'Asbahna wa asbahal-mulku lillah, wal-hamdu lillah, la ilaha illallahu wahdahu la sharika lah',
    englishMeaning: 'We have entered the morning and with it all dominion belongs to Allah. Praise be to Allah. There is no deity but Allah alone, with no partner.',
    source: 'Sahih Muslim',
    category: 'Morning & Evening',
    isBuiltIn: true,
  },
  {
    id: 'dua_evening',
    title: 'Evening Adhkar',
    arabicText: 'أَمْسَيْنَا وَأَمْسَى الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ، لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ',
    transliteration: 'Amsayna wa amsal-mulku lillah, wal-hamdu lillah, la ilaha illallahu wahdahu la sharika lah',
    englishMeaning: 'We have entered the evening and with it all dominion belongs to Allah. Praise be to Allah. There is no deity but Allah alone, with no partner.',
    source: 'Sahih Muslim',
    category: 'Morning & Evening',
    isBuiltIn: true,
  },
  {
    id: 'dua_after_wudu',
    title: 'After Ablution',
    arabicText: 'أَشْهَدُ أَنْ لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، وَأَشْهَدُ أَنَّ مُحَمَّدًا عَبْدُهُ وَرَسُولُهُ',
    transliteration: "Ashhadu an la ilaha illallahu wahdahu la sharika lah, wa ashhadu anna Muhammadan 'abduhu wa rasuluh",
    englishMeaning: 'I bear witness that there is no deity but Allah alone, with no partner, and I bear witness that Muhammad is His servant and Messenger.',
    source: 'Sahih Muslim',
    category: 'Purification',
    isBuiltIn: true,
  },
  {
    id: 'dua_after_adhan',
    title: 'After Adhan',
    arabicText: 'اللَّهُمَّ رَبَّ هَذِهِ الدَّعْوَةِ التَّامَّةِ وَالصَّلَاةِ الْقَائِمَةِ، آتِ مُحَمَّدًا الْوَسِيلَةَ وَالْفَضِيلَةَ، وَابْعَثْهُ مَقَامًا مَحْمُودًا الَّذِي وَعَدْتَهُ',
    transliteration: "Allahumma Rabba hadhihid-da'watit-tammah, was-salatil-qa'imah, ati Muhammadanil-wasilata wal-fadilah, wab'ath-hu maqaman mahmudanil-ladhi wa'adtah",
    englishMeaning: 'O Allah, Lord of this perfect call and established prayer, grant Muhammad the intercession and favour, and raise him to the praised station You have promised him.',
    source: 'Sahih al-Bukhari',
    category: 'Prayer',
    isBuiltIn: true,
  },
  {
    id: 'dua_istiftah',
    title: 'Opening Dua (Prayer)',
    arabicText: 'سُبْحَانَكَ اللَّهُمَّ وَبِحَمْدِكَ، وَتَبَارَكَ اسْمُكَ، وَتَعَالَى جَدُّكَ، وَلَا إِلَهَ غَيْرُكَ',
    transliteration: 'Subhanaka Allahumma wa bihamdik, wa tabarakasmuk, wa taʿala jadduk, wa la ilaha ghayruk',
    englishMeaning: 'Glory is to You, O Allah, and praise; blessed is Your name, exalted is Your majesty, and there is no deity other than You.',
    source: 'Sunan Abi Dawud',
    category: 'Prayer',
    isBuiltIn: true,
  },
  {
    id: 'dua_bathroom',
    title: 'Entering Bathroom',
    arabicText: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْخُبُثِ وَالْخَبَائِثِ',
    transliteration: "Allahumma inni a'udhu bika minal-khubuthi wal-khaba'ith",
    englishMeaning: 'O Allah, I seek refuge in You from the evil and evil-doers (male and female devils).',
    source: 'Sahih al-Bukhari & Muslim',
    category: 'Daily',
    isBuiltIn: true,
  },
  {
    id: 'dua_leaving_home',
    title: 'Leaving Home',
    arabicText: 'بِسْمِ اللَّهِ، تَوَكَّلْتُ عَلَى اللَّهِ، وَلَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ',
    transliteration: "Bismillah, tawakkaltu 'alallah, wa la hawla wa la quwwata illa billah",
    englishMeaning: 'In the name of Allah, I place my trust in Allah, and there is no might nor power except with Allah.',
    source: 'Sunan Abi Dawud & at-Tirmidhi',
    category: 'Daily',
    isBuiltIn: true,
  },
  {
    id: 'dua_entering_home',
    title: 'Entering Home',
    arabicText: 'بِسْمِ اللَّهِ وَلَجْنَا، وَبِسْمِ اللَّهِ خَرَجْنَا، وَعَلَى اللَّهِ رَبِّنَا تَوَكَّلْنَا',
    transliteration: 'Bismillahi walajna, wa bismillahi kharajna, wa ʿala Allahi Rabbina tawakkalna',
    englishMeaning: 'In the name of Allah we enter, in the name of Allah we leave, and upon Allah our Lord we place our trust.',
    source: 'Sunan Abi Dawud',
    category: 'Daily',
    isBuiltIn: true,
  },
  {
    id: 'dua_travel',
    title: 'Travel Dua',
    arabicText: 'سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَذَا وَمَا كُنَّا لَهُ مُقْرِنِينَ، وَإِنَّا إِلَى رَبِّنَا لَمُنْقَلِبُونَ',
    transliteration: 'Subhanal-ladhi sakhkhara lana hadha wa ma kunna lahu muqrinin, wa inna ila Rabbina lamunqalibun',
    englishMeaning: 'Glory to Him who has subjected this to us, and we could not have done it ourselves. And indeed, to our Lord we will return.',
    source: 'Sahih Muslim (Qur’an 43:13-14)',
    category: 'Daily',
    isBuiltIn: true,
  },
  {
    id: 'dua_istighfar',
    title: 'Sayyid al-Istighfar',
    arabicText: 'اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَهَ إِلَّا أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ، وَأَنَا عَلَى عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ، أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ، أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ، وَأَبُوءُ بِذَنْبِي فَاغْفِرْ لِي فَإِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ',
    transliteration: "Allahumma anta Rabbi la ilaha illa ant, khalaqtani wa ana 'abduk, wa ana 'ala 'ahdika wa wa'dika mastata't, a'udhu bika min sharri ma sana't, abu'u laka bini'matika 'alayy, wa abu'u bidhanbi faghfir li fa innahu la yaghfirudh-dhunuba illa ant",
    englishMeaning: 'O Allah, You are my Lord, there is no deity but You. You created me and I am Your servant, and I keep Your covenant as much as I can. I seek refuge in You from the evil I have done. I acknowledge Your favour upon me and I confess my sin, so forgive me, for none forgives sins except You.',
    source: 'Sahih al-Bukhari',
    category: 'Forgiveness',
    isBuiltIn: true,
  },
  {
    id: 'universal_1',
    title: 'Trust in Allah',
    arabicText: 'حَسْبِيَ اللَّهُ لَا إِلَهَ إِلَّا هُوَ عَلَيْهِ تَوَكَّلْتُ وَهُوَ رَبُّ الْعَرْشِ الْعَظِيمِ',
    transliteration: 'Hasbiyallahu la ilaha illa huwa alaihi tawakkaltu wa huwa rabbul arshil azeem',
    englishMeaning: 'Allah is sufficient for me. There is no deity except Him. I have placed my trust in Him, and He is the Lord of the Great Throne.',
    source: 'Sunan Abi Dawud',
    category: 'Reliance',
    isBuiltIn: true,
  },
  {
    id: 'universal_4',
    title: 'Relief from Anxiety',
    arabicText: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْهَمِّ وَالْحَزَنِ، وَأَعُوذُ بِكَ مِنَ الْعَجْزِ وَالْكَسَلِ',
    transliteration: "Allahumma inni a'oodhu bika minal hammi wal hazani, wa a'oodhu bika minal ajzi wal kasal",
    englishMeaning: 'O Allah, I seek refuge in You from anxiety and sorrow, and I seek refuge in You from weakness and laziness.',
    source: 'Sahih al-Bukhari',
    category: 'Distress',
    isBuiltIn: true,
  },
  {
    id: 'dua_night_waking',
    title: 'Waking at Night',
    arabicText: 'لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ، سُبْحَانَ اللَّهِ وَالْحَمْدُ لِلَّهِ وَلَا إِلَهَ إِلَّا اللَّهُ وَاللَّهُ أَكْبَرُ وَلَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ',
    transliteration: 'La ilaha illallahu wahdahu la sharika lah, lahul-mulku wa lahul-hamd, wa huwa ʿala kulli shayʾin qadir. Subhanallah, wal-hamdulillah, wa la ilaha illallah, wallahu akbar, wa la hawla wa la quwwata illa billah',
    englishMeaning: 'There is no deity but Allah alone, with no partner; His is the dominion and His is the praise, and He is capable of all things. Whoever says this on waking at night and then supplicates, his supplication is answered.',
    source: 'Sahih al-Bukhari',
    category: 'Sleep',
    isBuiltIn: true,
  },
  {
    id: 'dua_mulk',
    title: 'Surah Al-Mulk (before sleep)',
    arabicText: 'تَبَارَكَ الَّذِي بِيَدِهِ الْمُلْكُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ',
    transliteration: "Tabarakal-ladhi biyadihil-mulk, wa huwa 'ala kulli shay'in qadir",
    englishMeaning: 'Blessed is He in whose hand is the dominion, and He is over all things competent. Reminder: reciting Surah Al-Mulk each night is a means of protection.',
    source: 'Jami’ at-Tirmidhi (virtue of Al-Mulk)',
    category: 'Sleep',
    isBuiltIn: true,
  },
  {
    id: 'universal_1_sleep',
    title: 'Before Sleep',
    arabicText: 'بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا',
    transliteration: 'Bismika Allahumma amutu wa ahya',
    englishMeaning: 'In Your name, O Allah, I die and I live.',
    source: 'Sahih al-Bukhari',
    category: 'Sleep',
    isBuiltIn: true,
  },
];
